### ISSUE TITLE
Why Does Pipulate use Google Spreadsheets and Not SQLite3?

### ISSUE THREAD

**Issue by erikbgithub** [miklevin/Pipulate.com#6]
Hi Mike,

I'm writing here because it's more flexible to write in github (with markdown etc) instead of youtube/email/blog-without-login.

I'm a Python developer, but have not much idea about SEO or marketing people. For me it sounds so complicated that I have to run an extra server, a browser plugin and then pull the data in a quite heavy google docs spreadsheet. Why did you make that decision? I'd rather use a pip installable CLI with sqlite3 support. I thought maybe it's because marketing people think that way? For me it's really a reason to consider against using it when it is so heavy weight that I need a browser running all the time and can't reprocess the results with other tools.

**Comment by miklevin** [comment]
Don't think of it as the way marketing people think. Think of it as leaning on a multi-billion dollar infrastructure that can make the data infinitely more accessible, shareable, chart-able, graph-able, revision-track-able and the like. In other words, it's very similar to the Astronomer axiom: If you don't write it down, it didn't happen. The newer corollary became: If it's not on the Internet and find-able by Google, it doesn't exist (a fair corollary, given the state of the world today and the foreseeable future).

The realization of the modern corollary of the old astronomer's axiom is what drew me to SEO in the first place. It all makes just so much sense. But it all makes Google just so powerful. So if you ALREADY rely on their power for your career and livelihood, it only makes sense to leverage their tools. And no tool makes data equally accessible by both humans and machines in an easily and universally accessible way. Literally, you can pull up what SQL people might think of as a Ruby On Rails-like CRUD browser app. Well, Google Spreadsheets kicks a generic CRUD app's ass, because... well, it's Google and has their billion-dollar infrastructure keeping your data persistent and accessible in ways unprecedented in history. I mean, you can see other people as they go in and edit these things as almost like a screen share! You can do sophisticated mash-ups against all this data, since it's easily accessible with a Web-API. I'm not talking about an API that requires setting up multi-thousand-dollar SharePoint instances, as does Excel. Nor am I talking about difficult programming requiring you to be seasoned. It's the GDATA API which is already easy and widely supported, made even easier with the GSpread Github project.

Okay, I'll go on. This gets a bit heady, but once you absorb how much more valuable data is in a Google Spreadsheet for actually interacting with other human beings using the data (in addition to server-side mechanization), then you are ready to think about this:

If your data layer (what's in the Google Spreadsheet) ALSO defines it's own data monitoring, recording and scheduling tasks, then the business-logic layer only needs to drop in frequently enough to check if the recording has been done for the defined time-windows. Any server with sufficient access can do this. Multiple can even do it, and the first one in wins! 

The servers in this scenario become ultimately disposable. They are so transient, they can be instantiated as new instances on some virtual host on an as-needed basis. It could almost be like on-demand instances like old fashioned CGI programming, where the entire interpreter is loaded into server memory for each page-load. That's incredibly inefficient and I wouldn't recommend doing it, but Pipulate servers are precisely that generic, interchangeable and easily instantiated.

Final thought is your notion that you "it sounds so complicated that I have to run an extra server, a browser plugin and then pull the data in a quite heavy google docs spreadsheet."

There are several false presumptions here. They might have been true 5 or even 2 years ago, but no longer today. Things have just come into the realm of possible. First, the notion that running a server is complicated. Go look at my other project, Levinux. If that doesn't suit you, there's dozens of other approaches to EASILY running a server. The advantage here is YOU control the server code, and can make it do whatever you want without the limitation of say, Google App Script in GDocs, Google Application Engine or other platform-as-a-service vendor lock-in traps.

Ah, but Google Spreadsheets itself is a vendor lock-in trap itself, you say! Well, the second something that has all the attributes of Google Spreadsheets that makes it so wonderful comes into the free and open source world, we can swap Pipulate over to that, and SQLLite on transient disposable server-nodes ain't it. Amazon S3 or it's like would be a better pick... if they also came with easy spreadsheet access, a permission system, friendly APIs, yadda yadda. In short, we port the data layer to other things like Google Spreasheet when we can.

That'll be part of the fun of what plays out here.

And look more carefully at what you characterize as a browser extension. It's not. It's a bookmarklet, which is cross-browser compatible (unlike extensions) and within all the common browser and JavaScript standard specifications.

I could go on, but this gives the broad strokes. The real proof will be in seeing it go into daily use by SEOs. If it becomes the secret weapon of a new generation of SEOs, then I'm correct. If it doesn't, I'm wrong.
